vich_uploader:
  db_driver: orm
  mappings:
    company_images:
      uri_prefix: /uploads/companies
      upload_destination: "%kernel.project_dir%/public/uploads/companies"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
